# goal
uint8 WAVE_HAND = 0
# uint8 ... = 1

uint8 action
---
# result
uint8 SUCCESS = 0
uint8 FAILURE = 1

uint8 result
---
# feedback
# : [0 ~ 14]
#   - LeftShoulderPitch(13), LeftShoulderRoll(14), LeftShoulderYaw(15), LeftElbowPitch(16), LeftElbowRoll(17), LeftWristPitch(18), LeftWristYaw(19)
#   - RightShoulderPitch(20), RightShoulderRoll(21), RightShoulderYaw(22), RightElbowPitch(23), RightElbowRoll(24), RightWristPitch(25), RightWristYaw(26)
#   - WaistYaw(12)

JointInfo[] current_joint_angle
